# Generated by Django 3.2.5 on 2021-08-31 07:07

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accept', models.BooleanField(auto_created=True, default=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time')),
                ('modify_time', django_jalali.db.models.jDateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time')),
                ('message', models.TextField(help_text='This is comment message', max_length=1000, verbose_name='Comment Message')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
