# Generated by Django 3.2.5 on 2021-09-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
