# Generated by Django 3.2.5 on 2021-09-02 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210901_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, help_text='This is reply for this commnet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='account.comment', verbose_name='Reply'),
        ),
    ]
