# Generated by Django 3.2.5 on 2021-08-17 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ncode',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
