# Generated by Django 3.2.5 on 2021-08-17 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_ncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ncode2',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
