# Generated by Django 3.2.5 on 2021-08-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_ncode2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ncode2',
        ),
    ]
