# Generated by Django 3.2.5 on 2021-08-31 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time')),
                ('modify_time', django_jalali.db.models.jDateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time')),
                ('title_en', models.CharField(help_text='This is english name for discount item', max_length=150, verbose_name='English title')),
                ('title_fa', models.CharField(help_text='This is persian name for discount item', max_length=150, verbose_name='Persian title')),
                ('active_from', django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is start discount datetime ', verbose_name='From datetime')),
                ('active_to', django_jalali.db.models.jDateTimeField(help_text='This is expire discount datetime ', verbose_name='Expire datetime')),
                ('last_used', django_jalali.db.models.jDateTimeField(blank=True, default=None, help_text='This is last used of discount', null=True, verbose_name='Last Discount Used')),
                ('max_price', models.PositiveIntegerField(blank=True, default=None, help_text='This is max discount price item', null=True, verbose_name='Max Discount Price')),
                ('percent', models.PositiveIntegerField(help_text='This is discount percent', verbose_name='Discount Percent')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
            managers=[
                ('extra_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OffCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time')),
                ('modify_time', django_jalali.db.models.jDateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time')),
                ('title_en', models.CharField(help_text='This is english name for discount item', max_length=150, verbose_name='English title')),
                ('title_fa', models.CharField(help_text='This is persian name for discount item', max_length=150, verbose_name='Persian title')),
                ('active_from', django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is start discount datetime ', verbose_name='From datetime')),
                ('active_to', django_jalali.db.models.jDateTimeField(help_text='This is expire discount datetime ', verbose_name='Expire datetime')),
                ('last_used', django_jalali.db.models.jDateTimeField(blank=True, default=None, help_text='This is last used of discount', null=True, verbose_name='Last Discount Used')),
                ('max_price', models.PositiveIntegerField(blank=True, default=None, help_text='This is max discount price item', null=True, verbose_name='Max Discount Price')),
                ('percent', models.PositiveIntegerField(help_text='This is discount percent', verbose_name='Discount Percent')),
                ('code', models.CharField(default='fe592c77', help_text='This is unique code for discount', max_length=80, unique=True, verbose_name='Code for discount')),
                ('limit', models.PositiveIntegerField(default=1, help_text='This is limit of use off code', verbose_name='Limit Use')),
                ('for_users', models.ManyToManyField(blank=True, default=None, help_text='this is off code availble for selected users', null=True, to=settings.AUTH_USER_MODEL, verbose_name='For users')),
            ],
            options={
                'verbose_name': 'OFFCode',
                'verbose_name_plural': 'OFFCodes',
            },
            managers=[
                ('extra_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
