# Generated by Django 3.2.5 on 2021-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcode',
            name='code',
            field=models.CharField(default='ddb0c311', help_text='This is unique code for discount', max_length=80, unique=True, verbose_name='Code for discount'),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='percent',
            field=models.PositiveIntegerField(help_text='This is discount percent', verbose_name='Percent of off'),
        ),
    ]
