# Generated by Django 3.2.5 on 2021-09-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0009_alter_offcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offcode',
            name='code',
            field=models.CharField(default='aea2796f', help_text='This is unique code for discount', max_length=80, unique=True, verbose_name='Code for discount'),
        ),
    ]
