# Generated by Django 3.2.5 on 2021-08-31 07:07

import core.utils
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time')),
                ('modify_time', django_jalali.db.models.jDateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time')),
                ('name_fa', models.CharField(help_text='This is persian name category item', max_length=150, unique=True, verbose_name='Category FA Name')),
                ('name_en', models.CharField(help_text='This is english name category item', max_length=150, unique=True, verbose_name='Category EN Name')),
                ('image', models.ImageField(blank=True, help_text='This is image of category item', null=True, upload_to=core.utils.Controllers.Image.img_renamer, verbose_name='Category image')),
                ('url', models.URLField(help_text="This is url or link of category -> /category/'url'", unique=True, verbose_name='Link')),
                ('description_en', models.TextField(blank=True, default='This is test english category description', help_text='This is english description for this category', null=True, verbose_name='English description')),
                ('description_fa', models.TextField(blank=True, default='این متن تست برای توضیحات بخش دسته بندی است', help_text='This is persian description for this category', null=True, verbose_name='Persian description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
