# Generated by Django 3.2.5 on 2021-08-02 05:13

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('name_fa', models.CharField(help_text='This is persian name category item', max_length=150, unique=True, verbose_name='Category FA Name')),
                ('name_en', models.CharField(help_text='This is english name category item', max_length=150, unique=True, verbose_name='Category EN Name')),
                ('image', models.ImageField(blank=True, help_text='This is image of category item', null=True, upload_to=core.utils.Controllers.Image.img_renamer, verbose_name='Category image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
