# Generated by Django 3.2.5 on 2021-08-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(help_text="This is url or link of category -> /category/'url'", unique=True, verbose_name='Link'),
        ),
    ]
