# Generated by Django 3.2.5 on 2021-08-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(default='self.name_en'),
        ),
    ]
