# Generated by Django 3.2.5 on 2021-08-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(default=models.CharField(help_text='This is english name category item', max_length=150, unique=True, verbose_name='Category EN Name')),
        ),
    ]
