# Generated by Django 3.2.5 on 2021-08-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, default='This is test english category description', help_text='This is english description for this category', null=True, verbose_name='English description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fa',
            field=models.TextField(blank=True, default='این متن تست برای توضیحات بخش دسته بندی است', help_text='This is persian description for this category', null=True, verbose_name='Persian description'),
        ),
    ]
