# Generated by Django 3.2.5 on 2021-08-22 12:03

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20210804_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modify_time',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time'),
        ),
    ]
