# Generated by Django 3.2.5 on 2021-08-31 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20210831_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='relation',
        ),
        migrations.AddField(
            model_name='multiimages',
            name='rel',
            field=models.ForeignKey(default=1, help_text='This is relation for manay image', on_delete=django.db.models.deletion.CASCADE, to='image.image', verbose_name='images relation'),
            preserve_default=False,
        ),
    ]
