# Generated by Django 3.2.5 on 2021-08-31 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20210831_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiimages',
            name='rel',
        ),
        migrations.AddField(
            model_name='image',
            name='rel',
            field=models.ForeignKey(default=1, help_text='This is album relation for set image to this', on_delete=django.db.models.deletion.CASCADE, to='image.multiimages', verbose_name='Album relation'),
            preserve_default=False,
        ),
    ]
