# Generated by Django 3.2.5 on 2021-08-31 07:07

import core.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time')),
                ('modify_time', django_jalali.db.models.jDateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time')),
                ('title_fa', models.CharField(help_text='This is persian website title', max_length=90, verbose_name='Website Persian Title')),
                ('title_en', models.CharField(help_text='This is english website title', max_length=90, verbose_name='Website English Title')),
                ('sub_title_fa', models.CharField(blank=True, default='', help_text='This is persian website subtitle', max_length=90, null=True, verbose_name='Website Persian Subtitle')),
                ('sub_title_en', models.CharField(blank=True, default='', help_text='This is english website subtitle', max_length=90, null=True, verbose_name='Website English Subtitle')),
                ('short_description_fa', models.CharField(blank=True, default='', help_text='This is persian short description', max_length=360, null=True, verbose_name='Short Persian Description')),
                ('short_description_en', models.CharField(blank=True, default='', help_text='This is english short description', max_length=360, null=True, verbose_name='Short English Description')),
                ('description_en', models.TextField(blank=True, default='', help_text='This is english description for website', null=True, verbose_name='English description')),
                ('description_fa', models.TextField(blank=True, default='', help_text='This is persian description for website', null=True, verbose_name='Persian description')),
                ('address_fa', models.CharField(blank=True, default='Please enter your persian site address', help_text='This is persian address for your website', max_length=400, null=True, verbose_name='Persian Address')),
                ('address_en', models.CharField(blank=True, default='Please enter your persian site address', help_text='This is english address for your website', max_length=400, null=True, verbose_name='English Address')),
                ('url', models.URLField(blank=True, default='Please complete site url', help_text="This is url or link your website without 'http://'", max_length=90, null=True, verbose_name='Website Link')),
                ('version', models.FloatField(default=1.0, help_text='This is site version - default = 1.0', verbose_name='Site Version')),
                ('phone', models.CharField(help_text='This is IR phone number of sender', max_length=13, validators=[django.core.validators.RegexValidator(code='invalid IR phone number', message='Phone number must be entered in the true IR (iran) format.', regex='^(\\+98|0)?9\\d{9}$')], verbose_name='Phone')),
                ('email', models.EmailField(blank=True, help_text='This is email address for your website', max_length=80, null=True, verbose_name='Email Address')),
                ('about_fa', models.TextField(blank=True, default='Please enter persian about-us text', help_text='This is persian about text for your website', null=True, verbose_name='Persian About-us')),
                ('about_en', models.TextField(blank=True, default='Please enter english about-us text', help_text='This is english about text for your website', null=True, verbose_name='English About-us')),
                ('small_logo', models.ImageField(blank=True, default='', help_text='This is small image logo for website', null=True, upload_to=core.utils.Controllers.Image.img_renamer, verbose_name='Small Logo')),
                ('large_logo', models.ImageField(blank=True, default='', help_text='This is large image logo for website', null=True, upload_to=core.utils.Controllers.Image.img_renamer, verbose_name='Large Logo')),
                ('footer_msg_fa', models.CharField(blank=True, default='Please enter your desired message in the admin field - bottom message field', help_text='This is persian footer message', max_length=360, null=True, verbose_name='Persian Footer Message')),
                ('footer_msg_en', models.CharField(blank=True, default='Please complete footer message in admin - settings', help_text='This is english footer message', max_length=360, null=True, verbose_name='English Footer Message')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SochialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time')),
                ('modify_time', django_jalali.db.models.jDateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time')),
                ('name_fa', models.CharField(help_text='This is persian name of sochial accounts', max_length=60, verbose_name='Persian name')),
                ('name_en', models.CharField(help_text='This is english name of sochial accounts', max_length=60, verbose_name='English name')),
                ('url', models.URLField(help_text="This is link of sochial accounts -> sample : 'https://instagram.com/myaccounts' ", max_length=120, verbose_name='Link')),
                ('gb_ico', models.CharField(help_text="This is icon of sochial accounts from gorbeh icon -> sample : 'gb_telegram' ", max_length=50, validators=[django.core.validators.RegexValidator(code='invalid gb ico', message='GB Icon must be start with "gb_" and  end with alphabet char', regex='^[g][b][_]{1}[a-z]\\w+[a-z]+$')], verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Sochial Account',
                'verbose_name_plural': 'Sochial Accounts',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time')),
                ('modify_time', django_jalali.db.models.jDateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time')),
                ('is_read', models.BooleanField(default=False, help_text='This is Readed Message', verbose_name='Readed')),
                ('name', models.CharField(help_text='This is name of sender message', max_length=50, verbose_name='Sender Name')),
                ('phone', models.CharField(help_text='This is IR phone number of sender', max_length=13, validators=[django.core.validators.RegexValidator(code='invalid IR phone number', message='Phone number must be entered in the true IR (iran) format.', regex='^(\\+98|0)?9\\d{9}$')], verbose_name='Phone')),
                ('email', models.EmailField(blank=True, help_text='This is mail address of sender', max_length=80, null=True, verbose_name='Email')),
                ('msg', models.TextField(help_text='This is message of sender', verbose_name='Message')),
                ('user', models.ForeignKey(blank=True, help_text='This user id to send message', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User contact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
