# Generated by Django 3.2.5 on 2021-08-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SochialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('name_fa', models.CharField(help_text='This is persian name of sochial accounts', max_length=50, verbose_name='Persian name')),
                ('name_en', models.CharField(help_text='This is english name of sochial accounts', max_length=50, verbose_name='English name')),
                ('url', models.CharField(help_text='This is link of sochial accounts', max_length=50, verbose_name='Link')),
                ('gb_ico', models.CharField(help_text='This is icon of sochial accounts from gorbeh icon', max_length=50, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'SochialAccount',
                'verbose_name_plural': 'SochialAccounts',
            },
        ),
    ]
