# Generated by Django 3.2.5 on 2021-08-02 17:24

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(help_text='This is persian website title', max_length=90, verbose_name='Website Persian Title')),
                ('title_en', models.CharField(help_text='This is english website title', max_length=90, verbose_name='Website English Title')),
                ('sub_title_fa', models.CharField(blank=True, default='', help_text='This is persian website subtitle', max_length=90, null=True, verbose_name='Website Persian Subtitle')),
                ('sub_title_en', models.CharField(blank=True, default='', help_text='This is english website subtitle', max_length=90, null=True, verbose_name='Website English Subtitle')),
                ('short_description_fa', models.CharField(blank=True, default='', help_text='This is persian short description', max_length=360, null=True, verbose_name='Short Persian Description')),
                ('short_description_en', models.CharField(blank=True, default='', help_text='This is english short description', max_length=360, null=True, verbose_name='Short English Description')),
                ('description_en', models.TextField(blank=True, default='', help_text='This is english description for website', null=True, verbose_name='English description')),
                ('description_fa', models.TextField(blank=True, default='', help_text='This is persian description for website', null=True, verbose_name='Persian description')),
                ('address_fa', models.CharField(blank=True, default='Please enter your persian site address', help_text='This is persian address for your website', max_length=400, null=True, verbose_name='Persian Address')),
                ('address_en', models.CharField(blank=True, default='Please enter your persian site address', help_text='This is english address for your website', max_length=400, null=True, verbose_name='English Address')),
                ('url', models.CharField(blank=True, default='Please complete site url', help_text="This is url or link your website without 'http://'", max_length=90, null=True, verbose_name='Website Link')),
                ('version', models.FloatField(default=1.0, help_text='This is site version - default = 1.0', verbose_name='Site Version')),
                ('phone', models.CharField(blank=True, help_text='This is phone number for your website', max_length=11, null=True, verbose_name='Phone Number')),
                ('mobile', models.CharField(blank=True, help_text='This is mobile phone number for your website', max_length=11, null=True, verbose_name='Mobile Phone Number')),
                ('email', models.CharField(blank=True, help_text='This is email address for your website', max_length=11, null=True, verbose_name='Email Address')),
                ('about_fa', models.TextField(blank=True, default='Please enter persian about-us text', help_text='This is persian about text for your website', null=True, verbose_name='Persian About-us')),
                ('about_en', models.TextField(blank=True, default='Please enter english about-us text', help_text='This is english about text for your website', null=True, verbose_name='English About-us')),
                ('small_logo', models.ImageField(blank=True, default='', help_text='This is small image logo for website', null=True, upload_to=core.utils.Controllers.Image.img_renamer, verbose_name='Small Logo')),
                ('large_logo', models.ImageField(blank=True, default='', help_text='This is large image logo for website', null=True, upload_to=core.utils.Controllers.Image.img_renamer, verbose_name='Large Logo')),
                ('footer_msg_fa', models.CharField(blank=True, default='لطفا در قسمت ادمین - قسمت پیام پایینی - پیام مورد نظر خود را وارد کنید', help_text='This is persian footer message', max_length=360, null=True, verbose_name='Persian Footer Message')),
                ('footer_msg_en', models.CharField(blank=True, default='Please complete footer message in admin - settings', help_text='This is english footer message', max_length=360, null=True, verbose_name='English Footer Message')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SochialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('name_fa', models.CharField(help_text='This is persian name of sochial accounts', max_length=50, verbose_name='Persian name')),
                ('name_en', models.CharField(help_text='This is english name of sochial accounts', max_length=50, verbose_name='English name')),
                ('url', models.CharField(help_text='This is link of sochial accounts', max_length=50, verbose_name='Link')),
                ('gb_ico', models.CharField(help_text='This is icon of sochial accounts from gorbeh icon', max_length=50, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'SochialAccount',
                'verbose_name_plural': 'SochialAccounts',
            },
        ),
    ]
