# Generated by Django 3.2.5 on 2021-08-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='email',
            field=models.CharField(blank=True, help_text='This is email address for your website', max_length=80, null=True, verbose_name='Email Address'),
        ),
    ]
