# Generated by Django 3.2.5 on 2021-08-21 07:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0002_alter_site_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This is name of sender message', max_length=50, verbose_name='Sender Name')),
                ('phone', models.CharField(help_text='This is phone number of sender', max_length=13, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone')),
                ('email', models.CharField(blank=True, help_text='This is mail address of sender', max_length=80, null=True, verbose_name='Email')),
                ('msg', models.TextField(help_text='This is message of sender', verbose_name='Message')),
                ('user', models.ForeignKey(blank=True, help_text='This user id to send message', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User contact')),
            ],
        ),
    ]
