# Generated by Django 3.2.5 on 2021-08-21 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, help_text='This is mail address of sender', max_length=80, null=True, validators=[django.core.validators.EmailValidator], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='This is phone number of sender', max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the true format.', regex='^\\+?1?\\d{10,13}$')], verbose_name='Phone'),
        ),
    ]
