# Generated by Django 3.2.5 on 2021-08-15 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='This is created time', verbose_name='Created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time'),
        ),
    ]
