# Generated by Django 3.2.5 on 2021-08-22 12:03

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='modify_time',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='create_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='modify_time',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='status',
            name='create_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='status',
            name='modify_time',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time'),
        ),
    ]
