# Generated by Django 3.2.5 on 2021-08-23 12:13

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210822_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recepie_id',
            field=models.CharField(default='6944064', help_text='This is recepie id for this order', max_length=64, verbose_name='Recepie ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_datetime',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=None, help_text='This is payment datetime', null=True, verbose_name='Payment Datetime'),
        ),
    ]
