# Generated by Django 3.2.5 on 2021-08-31 07:07

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('discount', '0001_initial'),
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time')),
                ('modify_time', django_jalali.db.models.jDateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time')),
                ('title_en', models.CharField(help_text='This is english name of product item', max_length=150, verbose_name='English title')),
                ('title_fa', models.CharField(help_text='This is persian name of product item', max_length=150, verbose_name='Persian title')),
                ('short_description_en', models.CharField(help_text='This is english short description of product item', max_length=400, verbose_name='English short description')),
                ('short_description_fa', models.CharField(help_text='This is persian short description of product item', max_length=400, verbose_name='Persian short description')),
                ('description_en', models.TextField(help_text='This is english description of product item', verbose_name='English description')),
                ('description_fa', models.TextField(help_text='This is persian description of product item', verbose_name='Persian description')),
                ('price', models.PositiveIntegerField(help_text='This is price item', verbose_name='Price item')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='This is count of view products', verbose_name='View counts')),
                ('is_offer', models.BooleanField(default=False, help_text='This is status of offer product', verbose_name='Offer')),
                ('count_inventory', models.PositiveIntegerField(default=1, help_text='This is count of item in inventory', verbose_name='Count In Inventory')),
                ('count_buy', models.PositiveIntegerField(default=0, help_text='This is count of buy item', verbose_name='Count Of Buy')),
                ('url', models.URLField(default=core.utils.Controllers.Product.url_creator, help_text="This is url or link name item -> /products/'url'", unique=True, verbose_name='Link')),
                ('category', models.ForeignKey(help_text='This is category of product', on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Category of product')),
                ('discount', models.ForeignKey(blank=True, default=None, help_text='This is discount for product item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.discount', verbose_name='Discount')),
                ('image', models.OneToOneField(help_text='This is images list of product item', on_delete=django.db.models.deletion.CASCADE, to='image.multiimages', verbose_name='Product Images')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
            managers=[
                ('extra_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
