# Generated by Django 3.2.5 on 2021-08-02 05:13

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time')),
                ('modify_time', models.DateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('title_en', models.CharField(help_text='This is english name of product item', max_length=150, verbose_name='English title')),
                ('title_fa', models.CharField(help_text='This is persian name of product item', max_length=150, verbose_name='Persian title')),
                ('description_en', models.TextField(help_text='This is english description of product item', verbose_name='English description')),
                ('description_fa', models.TextField(help_text='This is persian description of product item', verbose_name='Persian description')),
                ('price', models.IntegerField(help_text='This is price item', verbose_name='Price item')),
                ('discount', models.IntegerField(help_text='This is discount of item', verbose_name='Discount item')),
                ('image', models.ImageField(help_text='This is image of product item', upload_to=core.utils.Controllers.Image.img_renamer, verbose_name='Product Image')),
                ('view_count', models.IntegerField(default=0, help_text='This is count of view products', verbose_name='View counts')),
                ('category', models.ForeignKey(help_text='This is category of product', on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Category of product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
            managers=[
                ('extra_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
