# Generated by Django 3.2.5 on 2021-08-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(default=False, help_text='This is status of offer product', verbose_name='Offer'),
        ),
    ]
