# Generated by Django 3.2.5 on 2021-08-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_inventory',
            field=models.IntegerField(default=15, help_text='This is count of item in inventory', verbose_name='Count In Inventory'),
            preserve_default=False,
        ),
    ]
