# Generated by Django 3.2.5 on 2021-08-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(default='', help_text='This is english short description of product item', max_length=400, verbose_name='English short description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_fa',
            field=models.CharField(default='', help_text='This is persian short description of product item', max_length=400, verbose_name='Persian short description'),
            preserve_default=False,
        ),
    ]
