# Generated by Django 3.2.5 on 2021-08-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_count_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_buy',
            field=models.IntegerField(default=0, help_text='This is count of buy item', verbose_name='Count Of Buy'),
        ),
    ]
