# Generated by Django 3.2.5 on 2021-08-03 08:13

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_count_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default=core.utils.Controllers.Product.url_creator, help_text='This is number of url link item', max_length=10, verbose_name='Link'),
        ),
    ]
