# Generated by Django 3.2.5 on 2021-08-07 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20210804_1756'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='This is english name for discount item', max_length=150, verbose_name='English title')),
                ('title_fa', models.CharField(help_text='This is persian name for discount item', max_length=150, verbose_name='Persian title')),
                ('active_from', models.DateTimeField(auto_now_add=True, help_text='This is start discount datetime ', verbose_name='From datetime')),
                ('active_to', models.DateTimeField(auto_now_add=True, help_text='This is expire discount datetime ', verbose_name='Expire datetime')),
                ('active', models.BooleanField(default=True, help_text='This is time ', verbose_name='Is Active')),
                ('count_use', models.PositiveIntegerField(default=1, help_text='This is count for use off code and expire', verbose_name='Count of use')),
                ('last_used', models.DateTimeField(blank=True, default=None, null=True)),
                ('max_price', models.PositiveIntegerField(blank=True, default=None, help_text='This is max discount price item', null=True, verbose_name='Max Discount Price')),
                ('percent', models.PositiveIntegerField(help_text='This is discount percent', verbose_name='Discount Percent')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='count_buy',
            field=models.PositiveIntegerField(default=0, help_text='This is count of buy item', verbose_name='Count Of Buy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count_inventory',
            field=models.PositiveIntegerField(help_text='This is count of item in inventory', verbose_name='Count In Inventory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='This is price item', verbose_name='Price item'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='This is count of view products', verbose_name='View counts'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, help_text='This is discount for product item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.discount', verbose_name='Discount'),
        ),
        migrations.CreateModel(
            name='OffCode',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.discount')),
                ('code', models.CharField(default='a0a068b5', help_text='This is unique code for discount', max_length=80, unique=True, verbose_name='Code for discount')),
                ('for_categories', models.ManyToManyField(blank=True, default=None, help_text='this is off code availble for selected categories', null=True, to='category.Category', verbose_name='For categories')),
                ('for_products', models.ManyToManyField(blank=True, default=None, help_text='this is off code availble for selected products', null=True, to='products.Product', verbose_name='For products')),
                ('for_users', models.ManyToManyField(blank=True, default=None, help_text='this is off code availble for selected users', null=True, to=settings.AUTH_USER_MODEL, verbose_name='For users')),
            ],
            options={
                'verbose_name': 'OFFCode',
                'verbose_name_plural': 'OFFCodes',
            },
            bases=('products.discount',),
        ),
    ]
