# Generated by Django 3.2.5 on 2021-08-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210807_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offcode',
            name='for_categories',
        ),
        migrations.RemoveField(
            model_name='offcode',
            name='for_products',
        ),
        migrations.AlterField(
            model_name='offcode',
            name='code',
            field=models.CharField(default='4551a080', help_text='This is unique code for discount', max_length=80, unique=True, verbose_name='Code for discount'),
        ),
    ]
