# Generated by Django 3.2.5 on 2021-08-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210807_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='active_to',
            field=models.DateTimeField(help_text='This is expire discount datetime ', verbose_name='Expire datetime'),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='code',
            field=models.CharField(default='7e49e2f4', help_text='This is unique code for discount', max_length=80, unique=True, verbose_name='Code for discount'),
        ),
    ]
