# Generated by Django 3.2.5 on 2021-08-22 12:03

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_offcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='active_from',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is start discount datetime ', verbose_name='From datetime'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='active_to',
            field=django_jalali.db.models.jDateTimeField(help_text='This is expire discount datetime ', verbose_name='Expire datetime'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='last_used',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='offcode',
            name='code',
            field=models.CharField(default='4e276fce', help_text='This is unique code for discount', max_length=80, unique=True, verbose_name='Code for discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, help_text='This is created time', verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modify_time',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, help_text='This is modified time', verbose_name='Modified time'),
        ),
    ]
